//=============== ESCRITORIO ==================
//CHART
export const escritorioFaltasDataChart = [
  { name: "Primero A", Alumnos: 25, Faltas: 10 },
  { name: "Primero B", Alumnos: 24, Faltas: 6 },
  { name: "Segundo A", Alumnos: 20, Faltas: 13 },
];

export const escritorioNotasDataChart = [
  { name: "Primero A", Alumnos: 25, Notas: 6 },
  { name: "Primero B", Alumnos: 24, Notas: 8 },
  { name: "Segundo A", Alumnos: 20, Notas: 7 },
];

export const configuracionesMock = {
  asignaturas: [
    {
      id: "1",
      idUser: "50",
      nombre: "Matemáticas",
      deshabilitado: "no",
      periodo: "4",
    },
    {
      id: "2",
      idUser: "50",
      nombre: "Lengua",
      deshabilitado: "no",
      periodo: "4",
    },
    {
      id: "6",
      idUser: "50",
      nombre: "Ingles",
      deshabilitado: "no",
      periodo: "4",
    },
  ],
  cursos: [
    {
      id: "5",
      idUser: "50",
      nombre: "Primero A",
      deshabilitado: "no",
      periodo: "4",
    },
    {
      id: "7",
      idUser: "50",
      nombre: "Primero B",
      deshabilitado: "no",
      periodo: "4",
    },
  ],
  evaluaciones: [
    {
      id: "5",
      idUser: "50",
      nombre: "1º",
      deshabilitado: "no",
      periodo: "4",
      tipo: "trimestral",
    },
    {
      id: "6",
      idUser: "50",
      nombre: "2º",
      deshabilitado: "no",
      periodo: "4",
      tipo: "trimestral",
    },
    {
      id: "7",
      idUser: "50",
      nombre: "3º",
      deshabilitado: "no",
      periodo: "4",
      tipo: "trimestral",
    },
    {
      id: "8",
      idUser: "50",
      nombre: "Parcial Ud. 1",
      deshabilitado: "no",
      periodo: "4",
      tipo: "examen",
    },
    {
      id: "14",
      idUser: "50",
      nombre: "Parcial 4",
      deshabilitado: "no",
      periodo: "4",
      tipo: "examen",
    },
    {
      id: "15",
      idUser: "50",
      nombre: "Eval Final",
      deshabilitado: "no",
      periodo: "4",
      tipo: "trimestral",
    },
  ],
  periodos: [
    {
      id: "1",
      nombre: "2019-2020",
      deshabilitado: "0",
    },
    {
      id: "2",
      nombre: "2020-2021",
      deshabilitado: "0",
    },
    {
      id: "3",
      nombre: "2021-2022",
      deshabilitado: "0",
    },
    {
      id: "4",
      nombre: "2022-2023",
      deshabilitado: "0",
    },
    {
      id: "5",
      nombre: "2023-2024",
      deshabilitado: "0",
    },
    {
      id: "6",
      nombre: "2024-2025",
      deshabilitado: "0",
    },
  ],
};

export const contactosDataMock = {
  accounts: [
    {
      id: "51",
      idUser: "50",
      nombre: "Alejandro",
      apellidos: "Ruiz Pineda",
      nacimiento: "2018-01-17",
      domicilio: "C/ El Peso",
      periodo: "4",
      nHermanos: "2",
      puesto: "",
      grupo: "A",
      localidad: "Lucena",
      cp: "14900",
      provincia: "Córdoba",
      foto: "",
      nombrePadre: "",
      telefonoPadre: "0",
      estudiosPadre: "",
      profesionPadre: "",
      nombreMadre: "",
      telefonoMadre: "0",
      estudiosMadre: "",
      profesionMadre: "",
      contactoUrgencia: "",
      telefonoUrgencia: "0",
    },
    {
      id: "52",
      idUser: "50",
      nombre: "María",
      apellidos: "Salazar del Espino",
      nacimiento: "2018-03-20",
      domicilio: "",
      periodo: "4",
      nHermanos: "0",
      puesto: "",
      grupo: "",
      localidad: "",
      cp: "0",
      provincia: "",
      foto: "",
      nombrePadre: "",
      telefonoPadre: "0",
      estudiosPadre: "",
      profesionPadre: "",
      nombreMadre: "",
      telefonoMadre: "0",
      estudiosMadre: "",
      profesionMadre: "",
      contactoUrgencia: "",
      telefonoUrgencia: "0",
    },
    {
      id: "53",
      idUser: "50",
      nombre: "Nayara",
      apellidos: "Pérez Pérez",
      nacimiento: "2015-06-15",
      domicilio: "",
      periodo: "4",
      nHermanos: "0",
      puesto: "",
      grupo: "",
      localidad: "",
      cp: "0",
      provincia: "",
      foto: "",
      nombrePadre: "",
      telefonoPadre: "0",
      estudiosPadre: "",
      profesionPadre: "",
      nombreMadre: "",
      telefonoMadre: "0",
      estudiosMadre: "",
      profesionMadre: "",
      contactoUrgencia: "",
      telefonoUrgencia: "0",
    },
  ],
  notas: [
    {
      id: "44",
      idUser: "50",
      idContacto: "51",
      evaluacion: "8",
      materia: "1",
      tipo: "examen",
      observaciones: "",
      valor: "8",
      periodo: "4",
    },
    {
      id: "45",
      idUser: "50",
      idContacto: "51",
      evaluacion: "14",
      materia: "1",
      tipo: "examen",
      observaciones: "",
      valor: "7",
      periodo: "4",
    },
    {
      id: "46",
      idUser: "50",
      idContacto: "51",
      evaluacion: "8",
      materia: "2",
      tipo: "examen",
      observaciones: "",
      valor: "9",
      periodo: "4",
    },
    {
      id: "47",
      idUser: "50",
      idContacto: "51",
      evaluacion: "14",
      materia: "2",
      tipo: "examen",
      observaciones: "",
      valor: "6",
      periodo: "4",
    },
    {
      id: "48",
      idUser: "50",
      idContacto: "51",
      evaluacion: "8",
      materia: "6",
      tipo: "examen",
      observaciones: "",
      valor: "8",
      periodo: "4",
    },
    {
      id: "49",
      idUser: "50",
      idContacto: "51",
      evaluacion: "14",
      materia: "6",
      tipo: "examen",
      observaciones: "",
      valor: "7",
      periodo: "4",
    },
    {
      id: "50",
      idUser: "50",
      idContacto: "52",
      evaluacion: "8",
      materia: "1",
      tipo: "examen",
      observaciones: "",
      valor: "7",
      periodo: "4",
    },
    {
      id: "51",
      idUser: "50",
      idContacto: "52",
      evaluacion: "14",
      materia: "1",
      tipo: "examen",
      observaciones: "",
      valor: "6",
      periodo: "4",
    },
    {
      id: "52",
      idUser: "50",
      idContacto: "52",
      evaluacion: "8",
      materia: "2",
      tipo: "examen",
      observaciones: "",
      valor: "6",
      periodo: "4",
    },
    {
      id: "53",
      idUser: "50",
      idContacto: "52",
      evaluacion: "14",
      materia: "2",
      tipo: "examen",
      observaciones: "",
      valor: "6",
      periodo: "4",
    },
    {
      id: "54",
      idUser: "50",
      idContacto: "52",
      evaluacion: "8",
      materia: "6",
      tipo: "examen",
      observaciones: "",
      valor: "7",
      periodo: "4",
    },
    {
      id: "55",
      idUser: "50",
      idContacto: "52",
      evaluacion: "14",
      materia: "6",
      tipo: "examen",
      observaciones: "",
      valor: "9",
      periodo: "4",
    },
    {
      id: "56",
      idUser: "50",
      idContacto: "53",
      evaluacion: "8",
      materia: "1",
      tipo: "examen",
      observaciones: "",
      valor: "8",
      periodo: "4",
    },
    {
      id: "57",
      idUser: "50",
      idContacto: "53",
      evaluacion: "14",
      materia: "1",
      tipo: "examen",
      observaciones: "",
      valor: "5",
      periodo: "4",
    },
    {
      id: "58",
      idUser: "50",
      idContacto: "53",
      evaluacion: "8",
      materia: "2",
      tipo: "examen",
      observaciones: "",
      valor: "5",
      periodo: "4",
    },
    {
      id: "59",
      idUser: "50",
      idContacto: "53",
      evaluacion: "14",
      materia: "2",
      tipo: "examen",
      observaciones: "",
      valor: "5",
      periodo: "4",
    },
    {
      id: "60",
      idUser: "50",
      idContacto: "53",
      evaluacion: "8",
      materia: "6",
      tipo: "examen",
      observaciones: "",
      valor: "7",
      periodo: "4",
    },
    {
      id: "61",
      idUser: "50",
      idContacto: "53",
      evaluacion: "14",
      materia: "6",
      tipo: "examen",
      observaciones: "",
      valor: "7",
      periodo: "4",
    },
  ],
  asistencias: [
    {
      id: "41",
      idUser: "50",
      idContacto: "51",
      fecha: "2022-09-07",
      valor: "1",
      obs: "",
      periodo: "4",
    },
    {
      id: "42",
      idUser: "50",
      idContacto: "51",
      fecha: "2022-10-23",
      valor: "1",
      obs: "",
      periodo: "4",
    },
    {
      id: "43",
      idUser: "50",
      idContacto: "51",
      fecha: "2022-01-16",
      valor: "1",
      obs: "",
      periodo: "4",
    },
    {
      id: "44",
      idUser: "50",
      idContacto: "52",
      fecha: "2022-12-18",
      valor: "2",
      obs: "",
      periodo: "4",
    },
    {
      id: "45",
      idUser: "50",
      idContacto: "52",
      fecha: "2022-09-08",
      valor: "2",
      obs: "",
      periodo: "4",
    },
    {
      id: "46",
      idUser: "50",
      idContacto: "53",
      fecha: "2022-01-10",
      valor: "3",
      obs: "",
      periodo: "4",
    },
  ],
  contactosContextoEscolar: [
    {
      id: "36",
      idUser: "50",
      idContacto: "51",
      responsable: "",
      despreocupado: "",
      periodo: "4",
      motivado: "",
      desmotivado: "",
      atento: "",
      distraido: "",
      reflexivo: "",
      impulsivo: "",
      independiente: "",
      dependiente: "",
      organizado: "",
      desorganizado: "",
      cursoRepetido: "",
      presentaAdaptacion: "",
      promocionaConAreasSuspensas: "",
      comprensionLectora: "",
      comprensionOral: "",
      expresionEscrita: "",
      expresionOral: "",
      calculo: "",
      resolucionDeProblemas: "",
      ortografia: "",
      vocabulario: "",
      interesAprendizaje: "",
      relacionAlumnos: "",
      habitosTrabajo: "",
      habitosEstudio: "",
      comportamiento: "",
      observacionesEscolares: "",
      curso: "5",
    },
    {
      id: "37",
      idUser: "50",
      idContacto: "52",
      responsable: "",
      despreocupado: "",
      periodo: "4",
      motivado: "",
      desmotivado: "",
      atento: "",
      distraido: "",
      reflexivo: "",
      impulsivo: "",
      independiente: "",
      dependiente: "",
      organizado: "",
      desorganizado: "",
      cursoRepetido: "",
      presentaAdaptacion: "",
      promocionaConAreasSuspensas: "",
      comprensionLectora: "",
      comprensionOral: "",
      expresionEscrita: "",
      expresionOral: "",
      calculo: "",
      resolucionDeProblemas: "",
      ortografia: "",
      vocabulario: "",
      interesAprendizaje: "",
      relacionAlumnos: "",
      habitosTrabajo: "",
      habitosEstudio: "",
      comportamiento: "",
      observacionesEscolares: "",
      curso: "5",
    },
    {
      id: "38",
      idUser: "50",
      idContacto: "53",
      responsable: "",
      despreocupado: "",
      periodo: "4",
      motivado: "",
      desmotivado: "",
      atento: "",
      distraido: "",
      reflexivo: "",
      impulsivo: "",
      independiente: "",
      dependiente: "",
      organizado: "",
      desorganizado: "",
      cursoRepetido: "",
      presentaAdaptacion: "",
      promocionaConAreasSuspensas: "",
      comprensionLectora: "",
      comprensionOral: "",
      expresionEscrita: "",
      expresionOral: "",
      calculo: "",
      resolucionDeProblemas: "",
      ortografia: "",
      vocabulario: "",
      interesAprendizaje: "",
      relacionAlumnos: "",
      habitosTrabajo: "",
      habitosEstudio: "",
      comportamiento: "",
      observacionesEscolares: "",
      curso: "7",
    },
  ],
  contactosContextoFamiliar: [
    {
      id: "18",
      idUser: "50",
      idContacto: "51",
      aceptaSituacionHijo: "",
      conocenCausasACNEAE: "",
      excesivaProteccion: "",
      refuerzanLogros: "",
      castiganConductasDisruptivas: "",
      dialoganHijo: "",
      presentanColaboracion: "",
      demandanReunionesTutor: "",
      colaboranSoloSiTutorLoPide: "",
      organizanTiempoDeEstudio: "",
      refuerzanAprendizaje: "",
      controlanEstudioDiario: "",
      fallecimientoPadre: "",
      fallecimientoMadre: "",
      desempleoPadre: "",
      desempleoMadre: "",
      custodiaPadre: "",
      custodiaMadre: "",
      custodiaAbuelos: "",
      custodiaOtros: "",
      personasConvivenSenoFamiliar: "",
      observacionesFamiliares: "",
      periodo: "4",
    },
    {
      id: "19",
      idUser: "50",
      idContacto: "52",
      aceptaSituacionHijo: "",
      conocenCausasACNEAE: "",
      excesivaProteccion: "",
      refuerzanLogros: "",
      castiganConductasDisruptivas: "",
      dialoganHijo: "",
      presentanColaboracion: "",
      demandanReunionesTutor: "",
      colaboranSoloSiTutorLoPide: "",
      organizanTiempoDeEstudio: "",
      refuerzanAprendizaje: "",
      controlanEstudioDiario: "",
      fallecimientoPadre: "",
      fallecimientoMadre: "",
      desempleoPadre: "",
      desempleoMadre: "",
      custodiaPadre: "",
      custodiaMadre: "",
      custodiaAbuelos: "",
      custodiaOtros: "",
      personasConvivenSenoFamiliar: "",
      observacionesFamiliares: "",
      periodo: "4",
    },
    {
      id: "20",
      idUser: "50",
      idContacto: "53",
      aceptaSituacionHijo: "",
      conocenCausasACNEAE: "",
      excesivaProteccion: "",
      refuerzanLogros: "",
      castiganConductasDisruptivas: "",
      dialoganHijo: "",
      presentanColaboracion: "",
      demandanReunionesTutor: "",
      colaboranSoloSiTutorLoPide: "",
      organizanTiempoDeEstudio: "",
      refuerzanAprendizaje: "",
      controlanEstudioDiario: "",
      fallecimientoPadre: "",
      fallecimientoMadre: "",
      desempleoPadre: "",
      desempleoMadre: "",
      custodiaPadre: "",
      custodiaMadre: "",
      custodiaAbuelos: "",
      custodiaOtros: "",
      personasConvivenSenoFamiliar: "",
      observacionesFamiliares: "",
      periodo: "4",
    },
  ],
  contactosContextoMedico: [
    {
      id: "19",
      idUser: "50",
      idContacto: "51",
      tratamientoMedico: "",
      tratamientoPsicologico: "",
      alergias: "",
      deficitAuditivo: "",
      deficitVisual: "",
      deficitTactil: "",
      deficitRespiratorio: "",
      deficitCardiaco: "",
      deficitMotorico: "",
      deficitObs: "",
      observacionesMedicas: "",
      periodo: "4",
      enfermedades: "",
    },
    {
      id: "20",
      idUser: "50",
      idContacto: "52",
      tratamientoMedico: "",
      tratamientoPsicologico: "",
      alergias: "",
      deficitAuditivo: "",
      deficitVisual: "",
      deficitTactil: "",
      deficitRespiratorio: "",
      deficitCardiaco: "",
      deficitMotorico: "",
      deficitObs: "",
      observacionesMedicas: "",
      periodo: "4",
      enfermedades: "",
    },
    {
      id: "21",
      idUser: "50",
      idContacto: "53",
      tratamientoMedico: "",
      tratamientoPsicologico: "",
      alergias: "",
      deficitAuditivo: "",
      deficitVisual: "",
      deficitTactil: "",
      deficitRespiratorio: "",
      deficitCardiaco: "",
      deficitMotorico: "",
      deficitObs: "",
      observacionesMedicas: "",
      periodo: "4",
      enfermedades: "",
    },
  ],
  cursos: [
    {
      id: "5",
      idUser: "50",
      nombre: "Primero A",
      deshabilitado: "no",
      periodo: "4",
    },
    {
      id: "7",
      idUser: "50",
      nombre: "Primero B",
      deshabilitado: "no",
      periodo: "4",
    },
  ],
  periodos: [
    {
      id: "1",
      nombre: "2019-2020",
      deshabilitado: "0",
    },
    {
      id: "2",
      nombre: "2020-2021",
      deshabilitado: "0",
    },
    {
      id: "3",
      nombre: "2021-2022",
      deshabilitado: "0",
    },
    {
      id: "4",
      nombre: "2022-2023",
      deshabilitado: "0",
    },
    {
      id: "5",
      nombre: "2023-2024",
      deshabilitado: "0",
    },
    {
      id: "6",
      nombre: "2024-2025",
      deshabilitado: "0",
    },
  ],
};
